global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'cloudrun'
    kubernetes_sd_configs:
      - role: endpoints
    relabel_configs:
      - source_labels: [__meta_kubernetes_service_name, __meta_kubernetes_namespace]
        target_label: cloudrun_service
      - source_labels: [__meta_kubernetes_pod_name]
        target_label: cloudrun_pod
