name: Prometheus Monitoring

# on:
#   push:
#     branches:
#       - main
# env:
#   PROJECT_ID: '${{ secrets.GCP_PROJECTID }}' # TODO: update Google Cloud project id
#   GCR_LOCATION:  '${{ secrets.GCP_GCR_LOCATION }}' # TODO: update Artifact Registry location
#   SERVICE: '${{ secrets.GCP_SERVICE_NAME }}' # TODO: update Cloud Run service name
#   REGION: '${{ secrets.GCP_REGION }}' # TODO: update Cloud Run service region
      

# jobs:
#   deploy-with-sidecar:
#     permissions:
#         contents: 'read'
#         id-token: 'write'
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v3
#       - name: Google Auth
#         id: auth
#         uses: 'google-github-actions/auth@v2'
#         with:
#           credentials_json: '${{ secrets.GCP_CREDENTIALS }}'
#       - name: Build and deploy Cloud Run service
#         uses: google-github-actions/setup-gcloud@v2
#         with:
#           name: jensen-micro-service
#           region: europe-west4
#           image: us-docker.pkg.dev/cloudrun/container/prometheus-to-sd:latest
#           annotations: |
#             run.googleapis.com/container-dependencies: '{"collector":["app"]}'
#       - name: Enable Cloud Monitoring
#         run: gcloud services enable monitoring.googleapis.com
#       - name: Create Managed Service for Prometheus instance
#         run: gcloud monitoring managed-prometheus instances create jensen-prometheus --region=europe-west4
#       - name: Add Prometheus scrape target
#         run: |
#           gcloud monitoring managed-prometheus scrape-configs create --instance=jensen-prometheus --scrape-config='{
#             "job_name": "jensen-micro-service",
#             "scrape_interval": "15s",
#             "static_configs": [
#               {
#                 "targets": ["https://jensen-micro-service-dot-jensen-dev.run.app/metrics"],
#                 "labels": {
#                   "app": "jensen-micro-service",
#                   "region": "europe-west4"
#                 }
#               }
#             ]
#           }'

