name: Prometheus Monitoring

on:
  push:
    branches:
      - main

jobs:
  deploy-with-sidecar:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Login to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GOOGLE_CLOUD_CREDENTIALS }}
      - name: Build and deploy Cloud Run service
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          name: jensen-micro-service
          region: europe-west4
          image: us-docker.pkg.dev/cloudrun/container/prometheus-to-sd:latest
          annotations: |
            run.googleapis.com/container-dependencies: '{"collector":["app"]}'
      - name: Enable Cloud Monitoring
        run: gcloud services enable monitoring.googleapis.com
      - name: Create Managed Service for Prometheus instance
        run: gcloud monitoring managed-prometheus instances create jensen-prometheus --region=europe-west4
      - name: Add Prometheus scrape target
        run: |
          gcloud monitoring managed-prometheus scrape-configs create --instance=jensen-prometheus --scrape-config='{
            "job_name": "jensen-micro-service",
            "scrape_interval": "15s",
            "static_configs": [
              {
                "targets": ["https://jensen-micro-service-dot-jensen-dev.run.app/metrics"],
                "labels": {
                  "app": "jensen-micro-service",
                  "region": "europe-west4"
                }
              }
            ]
          }'
